[build]
builder = "dockerfile"

[deploy]
numReplicas = 1
restartPolicyType = "ALWAYS"
healthcheckPath = "/health"
healthcheckTimeout = 30

[[services]]
name = "dataforseo-mcp"
port = 3000
protocol = "TCP"